sudo: required
services: 
  - docker

before_install:
  - docker build -t vedantdave77/docker-react -f Dockerfile.dev .   

scripts:
  - docker run -e CI=true vedantdave77/docker-react npm run test  #useful to exit test command right away (otherwise it continuously wait for the reply (p,q,o,enter))


#here,Explaination
# sudo for super user permission, 
# services tell travis to generate docker first 
# first install : install dockerfile.dev before doing anything to "." (current directory)
# -t <docker_name> command becuase its not easy to get the Docker_ID when we use the Travis. 